### ISSUE TITLE
my author information

### ISSUE THREAD

**Issue by ZonkedTundra** [ZonkedTundra/GoodThingsInComputing#9]
Need to add author details to the webpage

**Comment by ZonkedTundra** [comment]
linkedin: www.linkedin.com/in/zach-w-edwards
github: www.github.com/ZonkedTundra

**Comment by ZonkedTundra** [comment]
@tomBoddaert just added it

**Comment by tomBoddaert** [comment]
Thanks, I'll add your links, could you do Harvey's and he can do mine? And could you please message him on insta about that.

**Comment by skiing-gecko** [comment]
Yeah I'll do yours Tom. I also got hit by the Instagram ban so can't see any messages there. I'll create an issue when I'm back at college.
